config/routes.rb
Rails.application.routes.draw do
  get "reservation/new"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  get "users/account"
  get "users/profile"
  get "users/rooms"
  resources :users

  get "/" => "home#top"
  root to: "home#index"

  resources :rooms
  
  resources :rooms do
    collection do
      get "index"
    end
  end

  resources :rooms do
    resources :reservations, only: [:new, :create, :show]
  end
  resources :reservations, only: [:edit, :update, :destroy, :index]

  #resources :reservation


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar
  has_many :reservations
  has_many :rooms

       
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true #, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 },allow_blank: true #, format: { with: VALID_PASSWORD_REGEX }
  validates :introduction, length: { maximum: 200 } 
  attr_accessor :current_password

  def rooms
    return Room.where(user_id: self.id)
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  #def update
   # super do |user|
    #  break if user.errors.empty?
     # clean_up_passwords(user)
      #return redirect_to after_update_path_for(user)
    #end
  #end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:name,:avatar])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    flash[:notice] = 'アカウントを作成しました！編集ボタンからプロフィール画像と自己紹介文を登録できます。'
    users_account_path
  end

  # The path used after sign up for inactive accounts.
  def after_update_path_for(resource)
    flash[:notice] = 'アカウントを編集しました'
    users_account_path
  end

  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_signin_path_for(resource)
    flash[:notice] = 'ログインしました'
    root_path
  end

  def after_logout_path_for(resource)
    flash[:notice] = 'ログアウトしました'
    root_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def account
    @user = current_user
  end

  def profile
    @user = current_user
  end

  def rooms
    @user = current_user
    @rooms = @user.rooms
  end


  def update
    @user = User.find(params[:id])
    @introduction = params[:introduction]
    if @user.invalid?
      @error_messages = @user.errors.full_messages
      render template: "users/profile"
    elsif @user.update(user_params)
      flash[:notice]="プロフィールを更新しました"
      redirect_to users_account_path(current_user)
    end
  end


  private

  def user_params
  params.require(:user).permit(:email, :name, :introduction)
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class="user-container">

    <div class="user-tabs">
        <div class="tabs">
        <ul>
            <li class="active"><%= link_to("アカウント", users_account_path) %></li>
            <li><%= link_to("マイルーム", users_rooms_path) %></li>
            <li><%= link_to("予約済みルーム", reservations_path) %></li>
        </ul>
        </div>
    </div>

    <div class="user-view">
      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>
      <div class="view-box">
        <div class="view-account">
            <div class="view-content user-icon">
                <% if @user.avatar.attached? %>
                    <%= image_tag @user.avatar, class:"avatar-detail" %>
                <% else %>
                    <img class="avatar-detail" src="https://1.bp.blogspot.com/-K04KC6yK6Uc/X7zMjTPrDPI/AAAAAAABcdI/rg_FQJ194SYzrFROZ5mywsVLKZArAd8SwCNcBGAsYHQ/s726/shibasuberi_danbo-ru_girl.png"></td>
                <% end %>
            </div>
            <div class="view-content">
                <%= @user.name %>
            </div>
            <div class="view-content">
                <%= @user.email %>
            </div>
        </div>
        <div class="view-profile">
            <div class="introduction">
                <span class="introduction-title">プロフィール</span>
                <p><%= @user.introduction %></p>
            </div>
        </div>
        <div class="edit">
            <%= link_to "編集", edit_user_registration_path(@user) %>
        </div>
      </div>
    </div>


</div>

app/views/users/profile.html.erb
<div class="user-container">

    <div class="edit-tabs">
        <div class="tabs">
          <ul>
            <li><%= link_to("アカウント編集", edit_user_registration_path(@user)) %></li>
            <li class="active"><%= link_to("プロフィール編集", users_profile_path(@user)) %></li>
          </ul>
        </div>
    </div>
    
  <div class="user-view">
    <p class="notice"><%= notice %></p>
        <h2>プロフィール編集</h2>

    <div class="form-view">
      <div class="form-box">
        <%= form_with model: @user do |f| %>
          <% if @error_messages %>
            <div id="error_explanation">
              <h2><%= pluralize(@error_messages.count, "error") %> prohibited this reservation from being saved:</h2>
              <ul>
                <% @error_messages.each do |error| %>
                  <li><%= error %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

        <div class="field">
          <%= f.label :image_name,"プロフィール画像" %>
          <%= f.file_field :image_name %>
        </div>

        <div class="field">
          <%= f.label :introduction,"自己紹介" %>
          <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" %>
        </div>

        <div class="submitbtn">
          <%= f.submit "更新" %>
        </div>
      <% end %>

      <br /><div style="text-align: right;"><%= link_to "戻る", :back %></div>

    </div>
  </div>
</div>

app/views/users/rooms.html.erb
<div class="room-container">
    <div class="user-tabs">
      <div class="tabs">
        <ul>
            <li><%= link_to("アカウント", users_account_path) %></li>
            <li class="active"><%= link_to("マイルーム", users_rooms_path) %></li>
            <li><%= link_to("予約済みルーム", reservations_path) %></li>
        </ul>
      </div>
    </div>
  <div class="user-view">
    <div class="index-header">
      <h1>マイルーム一覧</h1>
      <%= link_to '新規登録', new_room_path %>
    </div>
    <div class="room-index">
      <table>
        <thead>
          <tr>
            <th>ルーム写真</th>
            <th>ルーム名</th>
            <th>場所</th>
            <th>ルーム紹介</th>
            <th>料金</th>
          </tr>
        </thead>

        <tbody>
          <% @user.rooms.each do |room| %>
          <tr>
            <% if room.image.attached? %>
              <td><%= image_tag room.image.variant( resize: "300" ) %></td>
            <% else %>
              <td><img class="image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg"></td>
            <% end %>
            <td><%= link_to room.name, room , class:"show-room"%></td>
            <td><%= room.address %></td>
            <td><%= room.introduction %></td>
            <td>¥<%= room.price %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>