config/routes.rb
Rails.application.routes.draw do
  get "reservation/new"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  get "users/account"
  get "users/profile"
  get "users/rooms"
  resources :users

  get "/" => "home#top"
  root to: "home#index"

  resources :rooms
  
  resources :rooms do
    collection do
      get "index"
    end
  end

  resources :rooms do
    resources :reservations, only: [:new, :create, :show]
  end
  resources :reservations, only: [:edit, :update, :destroy, :index]

  #resources :reservation


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :guests, presence: true

  def amount_days
    total_days = (self.end_date.to_i - self.start_date.to_i)/86400
    if total_days < 1
      total_days = 1
    else
      return total_days
    end
  end
  
  def amount_price
    self.total_price = room.price.to_i * self.total_days.to_i
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.where(params[user_id:current_user]).all
  end

  def show
    @reservation = Reservation.find_by(id: params[:id])
  end

  def new
    @reservation = Reservation.new(reservation_params)
    @room = Room.find(params[:room_id])
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @guests = params[:guests]
    if @reservation.invalid?
      @error_messages = @reservation.errors.full_messages
      render template: "rooms/show"
    else
      @user = current_user
      @reservation.total_days = @reservation.amount_days
      @reservation.total_price = @reservation.amount_price
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def create
    @room = Room.find(params[:room_id])
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash[:notice] = "予約完了しました"
      redirect_to room_reservation_path(@room.id,@reservation)
    else
      render :new
    end
  end


  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice] = "予約を削除しました"
    redirect_to :reservations
  end

  private
    def reservation_params
      params.require(:reservation).permit(:start_date,:end_date,:guests,:total_days,:total_price).merge(user_id: current_user.id, room_id: params[:room_id])
    end

end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/reservations/_form.html.erb
<%= render "error", obj: @reservation %>
<%= form_with model: @reservation, url: new_room_reservation_path(@room), method: :get do |f| %>
  <div class="field">
    <%= f.label :start_date, "チェックイン" %>
    <%= f.date_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date, "チェックアウト" %>
    <%= f.date_field :end_date %>
  </div>

  <div class="field">
    <%= f.label :guests, "宿泊人数" %>
    <%= f.number_field :guests %>
  </div>

  <div class="actions submitbtn">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to '戻る', rooms_path(@room) %>
<% end %>

app/views/reservations/index.html.erb
<div class="room-container">
    <div class="user-tabs">
      <div class="tabs">
        <ul>
            <li><%= link_to("アカウント", users_account_path) %></li>
            <li><%= link_to("マイルーム", users_rooms_path) %></li>
            <li class="active"><%= link_to("予約済みルーム", reservations_path) %></li>
        </ul>
      </div>
    </div>
    <div class="user-view">
        <div class="index-header">
          <h1>予約済みルーム一覧</h1>
          <%= link_to '新規登録', new_room_path %>
        </div>
      <div class="room-index">
      <table>
          <thead>
            <tr>
              <th>ルーム写真</th>
              <th>ルーム名</th>
              <th>チェックイン</th>
              <th>チェックアウト</th>
              <th>合計料金</th>
              <th>予約詳細</th>
            </tr>
          </thead>

          <tbody>
            <% @reservations.each do |reservation| %>
              <tr>
                <% if reservation.room.image.attached? %>
                  <td><%= image_tag reservation.room.image, size: '100x50', class:"image" %></td>
                <% else %>
                  <td><img class="image" src="https://1.bp.blogspot.com/-K04KC6yK6Uc/X7zMjTPrDPI/AAAAAAABcdI/rg_FQJ194SYzrFROZ5mywsVLKZArAd8SwCNcBGAsYHQ/s726/shibasuberi_danbo-ru_girl.png"></td>
                <% end %>
                <td><%= link_to reservation.room.name, room_path(reservation.room_id), class:"show-room" %></td>
                <td><%= reservation.start_date.to_s(:datetime_jp)  %></td>
                <td><%= reservation.end_date.to_s(:datetime_jp)  %></td>
                <td><%= reservation.total_price %></td>
                <td><%= link_to 'Show', room_reservation_path(reservation.room_id,reservation) %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="reservation-container">
  <div class="reservation-view">
    <p class="notice"><%= notice %></p>
    <h2>予約確認</h2>
    <div class="form-view">
      <div class="form-box">
        <h3>¥<%=@room.price%>/日</h3>

      <%= form_with model: [@room, @reservation] do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :room_id, value: @room.id %>
        <%= f.hidden_field :guests, value: @reservation.guests %>
        <%= f.hidden_field :total_days, value: @reservation.total_days %>
        <%= f.hidden_field :total_price, value: @reservation.total_price %>

        <div class="field">
          <%= f.label :start_date,"チェックイン" %>
          <%= f.date_field :start_date, value: @start_date, :readonly => true %>
        </div>

        <div class="field">
          <%= f.label :end_date,"チェックアウト" %>
          <%= f.date_field :end_date, value: @end_date, :readonly => true %>
        </div>

        <h4>使用日数：<%=@reservation.total_days%>日</h4>
        <h4>人数：<%=@reservation.guests%>人</h4>

        <div class="field">
          <%= f.label :total_price, "合計金額" %>
          <%= f.number_field :guests, value: @reservation.total_price, :readonly => true %>
        <div class="submitbtn">
          <%= f.submit '送信する' %>
        </div>
      <% end %>

      <%= form_with url: room_path(@room), method: :get do |f| %>
        <%= f.hidden_field :start_date, value: @start_date %>
        <%= f.hidden_field :end_date, value: @end_date %>
        <%= f.hidden_field :guests, value: @guests %>
        <div class="submitbtn">
        <%= f.submit '入力画面に戻る' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="form-view">
    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
  <div class="form-box">
   <div class="contents">
      <p>予約確定日時</p>
      <%= @reservation.created_at.to_s %>
   </div>
   <div class="contents">
   <p>開始日</p>
    <%= @reservation.start_date.to_s(:datetime_jp) %>
   </div>
   <div class="contents">
      <p>終了日</p>
      <%= @reservation.end_date.to_s(:datetime_jp) %>
   </div>
   <div class="contents">
      <p>滞在日数</p>
      <%= @reservation.total_days %>日間
    </div>
    <div class="contents">
      <p>合計金額</p>
      ¥<%= @reservation.total_price %>
    </div>
    <br /><div style="text-align: right;"><%= link_to "戻る", :back %></div>
  </div>
</div>