config/routes.rb
Rails.application.routes.draw do
  get "reservation/new"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  get "users/account"
  get "users/profile"
  get "users/rooms"
  resources :users

  get "/" => "home#top"
  root to: "home#index"

  resources :rooms
  
  resources :rooms do
    collection do
      get "index"
    end
  end

  resources :rooms do
    resources :reservations, only: [:new, :create, :show]
  end
  resources :reservations, only: [:edit, :update, :destroy, :index]

  #resources :reservation


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    has_one_attached :image
    has_many :reservations, dependent: :destroy
    belongs_to :user

    validates :name, presence: true
    validates :address, presence: true
    validates :introduction, presence: true,length: { maximum: 20 }
    validates :price, presence: true

    def self.search(address,keyword)
        if address.present? && keyword.present?
            @rooms = Room.where(["address LIKE ?", "%#{address}%"]).where(["address LIKE ? OR name LIKE ? OR introduction LIKE ?","%#{keyword}%","%#{keyword}%","%#{keyword}%"])
        elsif address.present?
            @rooms = Room.where(["address LIKE ?", "%#{address}%"])
        elsif keyword.present?
            @rooms = Room.where(["address LIKE ? OR name LIKE ? OR introduction LIKE ?","%#{keyword}%","%#{keyword}%","%#{keyword}%"])
        else
            @rooms = Room.none
        end
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_user, only: %i[ edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    if params[:address].present? || params[:keyword].present?
      @rooms = Room.search(params[:address],params[:keyword])
    else
      @rooms = Room.all
    end
  end

  def post
    @rooms = Room.where()
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @room = Room.find_by(id: params[:id])
    @reservation = Reservation.new
    @user = current_user.id

  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find_by(id: params[:id])
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :address, :introduction, :price, :user_id, :image)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div class="form-view">
      <div class="form-box">
<%= form_with(model: @room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "件") %> のエラーが発生したため予約できません。:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "ルーム名" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address,"所在地" %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :introduction, "紹介文" %>
    <%= form.text_area :introduction %>
  </div>

  <div class="field">
    <%= form.label :price, "金額" %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :image, "ルーム写真" %>
    <%= form.file_field :image %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions submitbtn">
    <%= form.submit %>
  </div>
  <div style="text-align: right;"><%= link_to '戻る', rooms_path %></div>
<% end %>
</div>
</div>
</div>

app/views/rooms/edit.html.erb
<p class="notice"><%= notice %></p>
<h2>ルーム編集</h2>

<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<p class="notice"><%= notice %></p>
<h1>検索結果：<%= @rooms.count %>件</h1>
<div class="room-container">
<div class="room-index">
<table>
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>場所</th>
      <th>ルーム紹介</th>
      <th>合計料金</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <% if room.image.attached? %>
          <td><%= image_tag room.image.variant( resize: "300" ) %></td>
        <% else %>
          <td><img class="image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg"></td>
        <% end %>
        <td><%= link_to room.name, room , class:"show-room"%></td>
        <td><%= room.address %></td>
        <td><%= room.introduction %></td>
        <td>¥<%= room.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/rooms/new.html.erb
<p class="notice"><%= notice %></p>
<h2>新規ルーム登録</h2>
<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<p class="notice"><%= notice %></p>
<div class="room-container">
  <div class="row">
    <div class="room-show">
      <div class="room-image">
        <% if @room.image.attached? %>
          <td><%= image_tag @room.image, class:"room-image" %></td>
        <% else %>
          <td><img class="room-image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg"></td>
        <% end %>
      </div>
      <div class="room-details">
        <div class="icon">
          <% if current_user.avatar.attached? %>
            <td><%= image_tag current_user.avatar, class:"avatar" %></td>
          <% else %>
            <td><img class="avatar" src="https://1.bp.blogspot.com/-K04KC6yK6Uc/X7zMjTPrDPI/AAAAAAABcdI/rg_FQJ194SYzrFROZ5mywsVLKZArAd8SwCNcBGAsYHQ/s726/shibasuberi_danbo-ru_girl.png"></td>
          <% end %>
        </div>
        <div class="room-profile">
          <p class="room-name"><%= @room.name %></p>
          <p class="room-address"><%= @room.address %></p>
        </div>
      </div>
      <div class="room-introduction">
        <p><%= @room.introduction %></p>
      </div>
      <div class="hostmenu", style="text-align: right;">
        <% if @room.user == current_user %>
          <%= link_to '編集する', edit_room_path(@room) %>
          <%= link_to '削除する', rooms_path, method: :delete, data: { confirm: '本当に良いですか?' } %>
        <% end %>
      </div>
    </div>

    <div class="reservation-new">
      <div class="reservation-nav">
        <h1>¥<%= @room.price %>/日</h1>
          <%= form_with model: @reservation, url: new_room_reservation_path(@room), method: :get do |f| %>
            <% if @error_messages %>
              <div id="error_explanation">
                <h2><%= pluralize(@error_messages.count, "件") %> のエラーが発生したため予約できません。:</h2>
                <ul>
                  <% @error_messages.each do |error| %>
                    <li><%= error %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
      
            <div class="field">
              <%= f.label :start_date,"チェックイン" %>
              <%= f.date_field :start_date, value: @start_date, min: Date.current, class:"reservation-input" %>
            </div>

            <div class="field">
              <%= f.label :end_date,"チェックアウト" %>
              <%= f.date_field :end_date, value: @end_date, min: Date.current,class:"reservation-input" %>
            </div>

            <div class="field">
              <%= f.label :guests,"宿泊人数" %>
              <%= f.number_field :guests, value: @guests,class:"reservation-input" %>
            </div>

            <div class="submitbtn">
              <%= f.submit  "予約確認へ" %>
            </div>
          <% end %>

          <br /><div style="text-align: right;"><%= link_to "戻る", rooms_path %></div>
      </div>
    </div>
  </div>
</div>